ln -s "$HOME/.dotfiles/shell/.zshrc" "$HOME/.zshrc"
ln -s "$HOME/.dotfiles/shell/.zshenv" "$HOME/.zshenv"
ln -s "$HOME/.dotfiles/editors/vscode/settings.json" "$HOME/.config/Code/User/settings.json"
ln -s "$HOME/.dotfiles/editors/vscode/snippets/typescript.json" "$HOME/.config/Code/User/snippets/typescript.json"
ln -s "$HOME/.dotfiles/editors/vscode/keybindings.json" "$HOME/.config/Code/User/keybindings.json"
ln -s "$HOME/.dotfiles/shell/zsh/themes/cdev.zsh-theme" "$ZSH_CUSTOM/themes/cdev.zsh-theme"